### PR TITLE
 add docker compose to deploy Moodle

### PR DESCRIPTION
**Pull request by zanssa**
add docker compose to deploy Moodle!

### CODE REVIEW

**Comment by thatnerdjosh** [comment]
@zanssa the base on your fork isn't correct (brings in Adam's changes as well due to wrong base), and the branch still isn't named according to the standards outlined in the email. If you'd like I could walk you through it :)

**Comment by zanssa** [comment]
@thatnerdjosh , Yes, please! I think it is gonna be better if we could add the instructions for sending pull requests in README for each repo. So, we could have a reference.

I was instructed in the email to send a pull request to develop branch and to add [WiP] or [DNM] when there was an issue in 
 the docker compose file. Now, the issue has been fixed, I don't think there will be a need to add these to the pull request. 

Will go ahead and close this request and send another one once I have the instructions for sending pull requests to the repos.

Thanks!

**Comment by thatnerdjosh** [comment]
Hello @zanssa, it may take me a little bit of time to get to writing a `CONTRIBUTING.md` as I also have a full time commitment for work and a couple of other volunteer projects which have some work I am in the process of working on but I have added this to my list.

The key components missing from the PR was to make a `feature` branch conformant with `git flow` and that branch needs to be based on develop (`git rebase develop`).

This guide https://www.hackspace.org.uk/resources/Hackspace%20Owners%20Manual/About%20this%20manual/contributing.md seems to be an excellent reference about the workflow, and I will add our own `CONTRIBUTING.md` in the near future.

Thanks!

**Comment by thatnerdjosh** [comment]
Also note, you are by no means expected to use the `git flow` or `git flow avh` command line tools as long as the naming and conventions are followed, as far as I understand from using them in the past they are merely convenience wrappers to make things easier. You can achieve the same naming scheme, rebasing, etc using `git` alone should you wish

**Pull request closed without merging**
